#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs


singularity exec docker://brainlife/mne:1.0.2 python3 main.py

cat << EOF > product.json
{
    "brainlife": [
       {
         "type": "image/png",
	       "name": "Ica components",
         "base64": "$(base64 -w 0 out_figs/ica.png)"
       }
]
}
EOF


